<?php
	namespace WebFX\Parser;
	
	use UniversalEditor\ObjectModels\Markup\MarkupObjectModel;
	
	use WebFX\System;
	
	use WebFX\WebNamespaceReference;
	use WebFX\WebScript;
	use WebFX\WebStyleSheet;
	use WebFX\WebVariable;
	use WebFX\WebPageMessage;
	
	use WebFX\WebControlAttribute;
	use WebFX\WebControlClientIDMode;
	
	use WebFX\HTMLControl;
	use WebFX\HTMLControls\HTMLControlLiteral;
	
	require("XMLParser.inc.php");
	
	class ControlLoader
	{
		public static $Messages;
		public static $Namespaces;
		
		public static function ParseChildren($elem, &$obj)
		{
			// our parent is a WebControl and we should parse its children as properties
			if (is_array($elem->Elements))
			{
				foreach ($elem->Elements as $elem1)
				{
					if (get_class($elem1) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
					if (!is_array($elem1->Elements))
					{
						trigger_error("\$elem1->Elements not array for tag '" . $elem1->Name . "'");
						continue;
					}
					
					foreach ($elem1->Elements as $elem2)
					{
						if (get_class($elem2) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
						$i = stripos($elem->Name, ":");
						$prefix = substr($elem2->Name, 0, $i);
						$name = substr($elem2->Name, $i + 1);
						
						if (isset(ControlLoader::$Namespaces[$prefix]) && ControlLoader::$Namespaces[$prefix] != "")
						{
							$realname = ControlLoader::$Namespaces[$prefix] . "\\" . $name;
						}
						else
						{
							$realname = $name;
						}
						if (class_exists($realname))
						{
							$obj1 = new $realname();
						}
						else
						{
							ControlLoader::$Messages[] = new WebPageMessage("Unknown class " . $realname . " (" . $prefix . ":" . $name . ")", WebPageMessageSeverity::Error);
							continue;
						}
						ControlLoader::LoadAttributes($elem2, $obj1);
						
						if ($obj1->ParseChildElements)
						{
							ControlLoader::ParseChildren($elem2, $obj1);
						}
						else
						{
							if (is_array($elem2->Elements))
							{
								foreach ($elem2->Elements as $elem3)
								{
									ControlLoader::LoadControl($elem3, $obj1);
								}
							}
						}
						
						$obj->{$elem1->Name}[] = $obj1;
					}
				}
			}
		}
		public static function LoadAttributes($elem, &$obj)
		{
			if (is_array($elem->Attributes))
			{
				foreach ($elem->Attributes as $attr)
				{
					$obj->{$attr->Name} = $attr->Value;
				}
			}
		}
		public static function LoadControl($elem, $parent)
		{
			if (get_class($elem) == "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement")
			{
				$i = stripos($elem->Name, ":");
				if ($i !== false)
				{
					$prefix = substr($elem->Name, 0, $i);
					$name = substr($elem->Name, $i + 1);
					
					if (isset(ControlLoader::$Namespaces[$prefix]) && ControlLoader::$Namespaces[$prefix] != "")
					{
						$realname = ControlLoader::$Namespaces[$prefix] . "\\" . $name;
					}
					else
					{
						$realname = $name;
					}
					
					if (class_exists($realname))
					{
						$obj = new $realname();
					}
					else
					{
						ControlLoader::$Messages[] = new WebPageMessage("Unknown class " . $realname . " (" . $prefix . ":" . $name . ")", WebPageMessageSeverity::Error);
						return;
					}
					ControlLoader::LoadAttributes($elem, $obj);
					
					if (is_subclass_of($obj, "WebFX\\WebControl") && $obj->ParseChildElements)
					{
						ControlLoader::ParseChildren($elem, $obj);
					}
					else
					{
						if (is_array($elem->Elements))
						{
							foreach ($elem->Elements as $elem1)
							{
								ControlLoader::LoadControl($elem1, $obj);
							}
						}
					}
					
					$obj->ParentObject = $parent;
					$parent->Controls[] = $obj;
				}
				else
				{
					$ctl = new HTMLControl();
					$ctl->TagName = $elem->Name;
					if (is_array($elem->Attributes))
					{
						foreach ($elem->Attributes as $attr)
						{
							$ctl->Attributes[] = new WebControlAttribute($attr->Name, $attr->Value);
						}
					}
					if (is_array($elem->Elements) && count($elem->Elements) > 0)
					{
						foreach ($elem->Elements as $elem1)
						{
							ControlLoader::LoadControl($elem1, $ctl);
						}
					}
					$ctl->ParentObject = $parent;
					$parent->Controls[] = $ctl;
				}
			}
			else if (get_class($elem) == "UniversalEditor\\ObjectModels\\Markup\\MarkupLiteralElement")
			{
				$parent->Controls[] = new HTMLControlLiteral($elem->Value);
			}
		}
	}
	ControlLoader::$Messages = array();
	
	class WebFXPage
	{
		/**
		 * The Page generated by this template.
		 * @var Page
		 */
		public $Page;
		
		public function OnInit()
		{
		}
	}
	
	class Page
	{
		public $CssClass;
		public $ClassName;
		
		public $Controls;
		
		public $FileName;
		
		public $MasterPage;
		
		public $References;
		public $Scripts;
		public $StyleSheets;
		
		public $Title;
		
		public $UseCompatibleRenderingMode;
		
		public function __construct()
		{
			$this->Controls = array();
			$this->References = array();
			$this->Scripts = array();
			$this->StyleSheets = array();
			$this->Variables = array();
			$this->UseCompatibleRenderingMode = false;
		}
		
		public function MergeMasterPageControls($controls)
		{
			$newControls = array();
			if ($this->MasterPage != null)
			{
				foreach ($controls as $control)
				{
					if (get_class($control) == "WebFX\\Controls\\SectionPlaceholder")
					{
						$pageControls = $this->Controls;
						foreach ($pageControls as $pageControl)
						{
							if (get_class($pageControl) != "WebFX\\Controls\\Section") continue;
							$newControls[] = $pageControl;
						}
					}
					else
					{
						$control->Controls = $this->MergeMasterPageControls($control->Controls);
						$newControls[] = $control;
					}
				}
			}
			return $newControls;
		}
		
		public function Render()
		{
			if (!$this->UseCompatibleRenderingMode)
			{
				header('Content-Type: application/xhtml+xml;charset=UTF-8');
			}
			
			$controls = $this->Controls;
			if ($this->MasterPage != null)
			{
				$controls = $this->MergeMasterPageControls($this->MasterPage->Controls);
			}
			
			foreach ($controls as $ctl)
			{
				$ctl->Initialize();
			}
			
			if (isset($this->ClassReference))
			{
				$this->ClassReference->Page = $this;
				if ($this->ClassReference != null)
				{
					if (method_exists($this->ClassReference, "OnInit"))
					{
						$retval = $this->ClassReference->OnInit();
						if ($retval === false) return;
					}
				}
			}
			
			$scripts = $this->Scripts;
			if ($this->MasterPage != null)
			{
				$scripts = $this->MasterPage->Scripts;
				foreach ($this->Scripts as $script)
				{
					$scripts[] = $script;
				}
			}
			
			$stylesheets = $this->StyleSheets;
			if ($this->MasterPage != null)
			{
				$stylesheets = $this->MasterPage->StyleSheets;
				foreach ($this->StyleSheets as $stylesheet)
				{
					$stylesheets[] = $stylesheet;
				}
			}
			
			$references = $this->References;
			if ($this->MasterPage != null)
			{
				$references = $this->MasterPage->References;
				foreach ($this->References as $reference)
				{
					$references[] = $reference;
				}
			}
			
			$variables = $this->Variables;
			if ($this->MasterPage != null)
			{
				$variables = $this->MasterPage->Variables;
				foreach ($this->Variables as $variable)
				{
					$variables[] = $variable;
				}
			}
			System::$Variables = $variables;
			
			if (!$this->UseCompatibleRenderingMode)
			{
				echo("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
				echo("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">");
			}
			else
			{
				echo("<!DOCTYPE html>");
			}
			
			$tagHTML = new HTMLControl();
			$tagHTML->TagName = "html";
			
			if (!$this->UseCompatibleRenderingMode)
			{
				$tagHTML->Attributes[] = new WebControlAttribute("xmlns", "http://www.w3.org/1999/xhtml");
				
				$referenceAlreadyUsed = array();
				foreach ($references as $reference)
				{
					$referenceAlreadyUsed[$reference->TagPrefix] = false;
				}
				foreach ($references as $reference)
				{
					if ($reference->NamespaceURL == "") continue;
					if ($referenceAlreadyUsed[$reference->TagPrefix]) continue;
					$tagHTML->Attributes[] = new WebControlAttribute("xmlns:" . $reference->TagPrefix, $reference->NamespaceURL);					
					$referenceAlreadyUsed[$reference->TagPrefix] = true;
				}
			}
			
			$tagHead = new HTMLControl();
			$tagHead->TagName = "head";
			
			// <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			
			$meta = new HTMLControl();
			$meta->TagName = "meta";
			$meta->HasContent = false;
			$meta->Attributes[] = new WebControlAttribute("name", "viewport");
			$meta->Attributes[] = new WebControlAttribute("content", "width=device-width,minimum-scale=1.0");
			$tagHead->Controls[] = $meta;
			
			$meta = new HTMLControl();
			$meta->TagName = "meta";
			$meta->HasContent = false;
			$meta->Attributes[] = new WebControlAttribute("http-equiv", "Content-Type");
			$meta->Attributes[] = new WebControlAttribute("content", "text/html; charset=utf-8");
			$tagHead->Controls[] = $meta;
			
			foreach ($scripts as $script)
			{
				$tagScript = new HTMLControl();
				$tagScript->ClientIDMode = WebControlClientIDMode::None;
				$tagScript->TagName = "script";
				
				if ($script->ContentType != "")
				{
					$tagScript->Attributes[] = new WebControlAttribute("type", $script->ContentType);
				}
				if ($script->FileName != "")
				{
					$tagScript->Attributes[] = new WebControlAttribute("src", System::ExpandRelativePath($script->FileName));
				}
				if ($script->Content != "")
				{
					$tagScript->InnerHTML = $script->Content;
				}
				$tagHead->Controls[] = $tagScript;
			}
			foreach ($stylesheets as $stylesheet)
			{
				$tagStyleSheet = new HTMLControl();
				$tagStyleSheet->ClientIDMode = WebControlClientIDMode::None;
				$tagStyleSheet->HasContent = false;
				$tagStyleSheet->TagName = "link";
				$tagStyleSheet->Attributes[] = new WebControlAttribute("rel", "stylesheet");
				$tagStyleSheet->Attributes[] = new WebControlAttribute("type", "text/css");
				if ($stylesheet->FileName != "")
				{
					$tagStyleSheet->Attributes[] = new WebControlAttribute("href", System::ExpandRelativePath($stylesheet->FileName));
				}
				if (isset($stylesheet->Content))
				{
					if ($stylesheet->Content != "")
					{
						$tagStyleSheet->InnerHTML = $stylesheet->Content;
					}
				}
				$tagHead->Controls[] = $tagStyleSheet;
			}
			$tagHTML->Controls[] = $tagHead;
			
			$tagBody = new HTMLControl();
			$tagBody->TagName = "body";
			
			if ($this->CssClass != "")
			{
				$tagBody->ClassList[] = $this->CssClass;
			}
			
			foreach ($controls as $ctl)
			{
				$tagBody->Controls[] = $ctl;
			}
			
			$tagHTML->Controls[] = $tagBody;
			$tagHTML->Render();
		}
		
		public static function FromMarkup($element, $parser)
		{
			$page = new Page();
			
			$attFileName = $element->GetAttribute("FileName");
			if ($attFileName != null)
			{
				$page->FileName = $attFileName->Value;
			}
			$attrMasterPageFileName = $element->GetAttribute("MasterPageFileName");
			if ($attrMasterPageFileName != null)
			{
				$page->MasterPage = $parser->GetMasterPageByFileName($attrMasterPageFileName->Value);
			}
			$attTitle = $element->GetAttribute("Title");
			if ($attTitle != null)
			{
				$page->Title = $attTitle->Value;
			}
			$attUseCompatibleRenderingMode = $element->GetAttribute("UseCompatibleRenderingMode");
			if ($attUseCompatibleRenderingMode != null)
			{
				$page->UseCompatibleRenderingMode = ($attUseCompatibleRenderingMode->Value == "true");
			}
			
			$tagScripts = $element->GetElement("Scripts");
			if ($tagScripts != null)
			{
				foreach ($tagScripts->Elements as $elem)
				{
					if (get_class($elem) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
					$attContentType = $elem->GetAttribute("ContentType");
					$contentType = "text/javascript";
					if ($attContentType != null) $contentType = $attContentType->Value;
					
					$page->Scripts[] = new WebScript($elem->GetAttribute("FileName")->Value, $contentType);
				}
			}
			$tagStyleSheets = $element->GetElement("StyleSheets");
			if ($tagStyleSheets != null)
			{
				foreach ($tagStyleSheets->Elements as $elem)
				{
					if (get_class($elem) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
					$attFileName = $elem->GetAttribute("FileName");
					if ($attFileName == null) continue;
					
					$page->StyleSheets[] = new WebStyleSheet($attFileName->Value);
				}
			}
			$tagVariables = $element->GetElement("Variables");
			if ($tagVariables != null)
			{
				foreach ($tagVariables->Elements as $elem)
				{
					if (get_class($elem) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
					$attName = $elem->GetAttribute("Name");
					if ($attName == null) continue;
					
					$value = "";
					$attValue = $elem->GetAttribute("Value");
					if ($attValue != null) $value = $attValue->Value;
					
					$page->Variables[] = new WebVariable($attName->Value, $value);
				}
			}
			
			$tagReferences = $element->GetElement("References");
			if ($tagReferences != null)
			{
				foreach ($tagReferences->Elements as $elem)
				{
					if (get_class($elem) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					
					$attTagPrefix = $elem->GetAttribute("TagPrefix");
					if ($attTagPrefix == null) continue;
					
					$attNamespacePath = $elem->GetAttribute("NamespacePath");
					if ($attNamespacePath == null) continue;
					
					$attNamespaceURL = $elem->GetAttribute("NamespaceURL");
					$namespaceURL = "";
					if ($attNamespaceURL != null) $namespaceURL = $attNamespaceURL->Value;
					
					$page->References[] = new WebNamespaceReference($attTagPrefix->Value, $attNamespacePath->Value, $namespaceURL);
				}
			}
			
			$references = $page->References;
			if ($page->MasterPage != null)
			{
				$references = $page->MasterPage->References;
				foreach ($page->References as $reference)
				{
					$references[] = $reference;
				}
			}
			foreach ($references as $reference)
			{
				ControlLoader::$Namespaces[$reference->TagPrefix] = $reference->NamespacePath;
			}
			
			$tagContent = $element->GetElement("Content");
			if ($tagContent != null)
			{
				foreach ($tagContent->Elements as $elem)
				{
					ControlLoader::LoadControl($elem, $page);
				}
			}
			
			$attrCssClass = $element->GetAttribute("CssClass");
			if ($attrCssClass != null)
			{
				$page->CssClass = $attrCssClass->Value;
			}
			
			$attrClassName = $element->GetAttribute("ClassName");
			if ($attrClassName != null)
			{
				$page->ClassName = $attrClassName->Value;
				
				if (class_exists($page->ClassName))
				{
					$page->ClassReference = new $page->ClassName();
					$page->IsPostback = ($_SERVER["REQUEST_METHOD"] == "POST");
					
					$arrPage = (array)$page;
					foreach ($arrPage as $name => $value)
					{
						$page->ClassReference->{$name} = $value;
					}

					if (is_array($page->ClassReference->Controls))
					{
						$page->Controls = $page->ClassReference->Controls;
					}
				}
				else
				{
					System::WriteErrorLog("Code-behind for '" . $page->ClassName . "' not found");
				}
			}
			return $page;
		}
	}
	
	class WebFXParser
	{
		public $MasterPages;
		public $Pages;
		
		public function GetMasterPageByFileName($filename)
		{
			foreach ($this->MasterPages as $page)
			{
				if ($page->FileName == $filename) return $page;
			}
			return null;
		}
		public function GetPageByFileName($filename)
		{
			foreach ($this->Pages as $page)
			{
				if ($page->FileName == $filename) return $page;
			}
			return null;
		}
		
		public function __construct()
		{
			$this->Clear();
		}
		
		public function Clear()
		{
			$this->MasterPages = array();
			$this->Pages = array();
		}
		
		/**
		 * Loads an XML file describing a portion or portions of the WebFX environment.
		 * @param string $filename The name of the XML file to load into the environment.
		 */
		public function LoadFile($filename)
		{
			$markup = MarkupObjectModel::FromFile($filename);
			
			$tagWebsite = $markup->GetElement("Website");
			if ($tagWebsite == null) return;
			
			$tagMasterPages = $tagWebsite->GetElement("MasterPages");
			
			if ($tagMasterPages != null)
			{
				foreach ($tagMasterPages->Elements as $element)
				{
					if (get_class($element) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					if ($element->Name == "MasterPage")
					{
						$this->MasterPages[] = Page::FromMarkup($element, $this);
					}
				}
			}
			
			$tagPages = $tagWebsite->GetElement("Pages");
			if ($tagPages != null)
			{
				foreach ($tagPages->Elements as $element)
				{
					if (get_class($element) != "UniversalEditor\\ObjectModels\\Markup\\MarkupTagElement") continue;
					if ($element->Name == "Page")
					{
						$this->Pages[] = Page::FromMarkup($element, $this);
					}
				}
			}
		}
	}
?>